import { v4 as uuidv4 } from 'uuid';

const today = new Date();
const daysFromToday = (n) => {
  const d = new Date(today);
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
};

export const mockItems = [
  {
    id: uuidv4(),
    name: 'Whole Milk',
    category: 'Dairy',
    quantity: 2,
    unit: 'Liters',
    entryDate: daysFromToday(-5),
    expiryDate: daysFromToday(1),
    status: 'active',
    notes: 'Full cream, from local farm',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Greek Yogurt',
    category: 'Dairy',
    quantity: 3,
    unit: 'Packs',
    entryDate: daysFromToday(-3),
    expiryDate: daysFromToday(-1),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Cheddar Cheese',
    category: 'Dairy',
    quantity: 200,
    unit: 'Grams',
    entryDate: daysFromToday(-10),
    expiryDate: daysFromToday(14),
    status: 'active',
    notes: 'Sharp cheddar',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Broccoli',
    category: 'Vegetables',
    quantity: 1,
    unit: 'Kg',
    entryDate: daysFromToday(-2),
    expiryDate: daysFromToday(3),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Baby Spinach',
    category: 'Vegetables',
    quantity: 250,
    unit: 'Grams',
    entryDate: daysFromToday(-4),
    expiryDate: daysFromToday(2),
    status: 'active',
    notes: 'Organic',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Cherry Tomatoes',
    category: 'Vegetables',
    quantity: 500,
    unit: 'Grams',
    entryDate: daysFromToday(-1),
    expiryDate: daysFromToday(6),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Red Apples',
    category: 'Fruits',
    quantity: 6,
    unit: 'Pieces',
    entryDate: daysFromToday(-3),
    expiryDate: daysFromToday(10),
    status: 'active',
    notes: 'Fuji variety',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Bananas',
    category: 'Fruits',
    quantity: 5,
    unit: 'Pieces',
    entryDate: daysFromToday(-1),
    expiryDate: daysFromToday(4),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Strawberries',
    category: 'Fruits',
    quantity: 400,
    unit: 'Grams',
    entryDate: daysFromToday(-2),
    expiryDate: daysFromToday(-1),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Basmati Rice',
    category: 'Grains',
    quantity: 2,
    unit: 'Kg',
    entryDate: daysFromToday(-30),
    expiryDate: daysFromToday(180),
    status: 'active',
    notes: 'Long grain, premium',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Whole Wheat Bread',
    category: 'Grains',
    quantity: 1,
    unit: 'Packs',
    entryDate: daysFromToday(-3),
    expiryDate: daysFromToday(4),
    status: 'active',
    notes: '',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Oats',
    category: 'Grains',
    quantity: 500,
    unit: 'Grams',
    entryDate: daysFromToday(-14),
    expiryDate: daysFromToday(90),
    status: 'active',
    notes: 'Rolled oats, gluten-free',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Orange Juice',
    category: 'Beverages',
    quantity: 1,
    unit: 'Liters',
    entryDate: daysFromToday(-5),
    expiryDate: daysFromToday(2),
    status: 'active',
    notes: 'Freshly squeezed',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Sparkling Water',
    category: 'Beverages',
    quantity: 6,
    unit: 'Bottles',
    entryDate: daysFromToday(-7),
    expiryDate: daysFromToday(120),
    status: 'active',
    notes: 'Lemon flavored',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Chicken Breast',
    category: 'Meat',
    quantity: 500,
    unit: 'Grams',
    entryDate: daysFromToday(-1),
    expiryDate: daysFromToday(1),
    status: 'active',
    notes: 'Fresh, not frozen',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Salmon Fillet',
    category: 'Meat',
    quantity: 300,
    unit: 'Grams',
    entryDate: daysFromToday(-2),
    expiryDate: daysFromToday(0),
    status: 'active',
    notes: 'Atlantic salmon',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Butter',
    category: 'Dairy',
    quantity: 250,
    unit: 'Grams',
    entryDate: daysFromToday(-7),
    expiryDate: daysFromToday(21),
    status: 'active',
    notes: 'Unsalted',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Almond Milk',
    category: 'Beverages',
    quantity: 1,
    unit: 'Liters',
    entryDate: daysFromToday(-2),
    expiryDate: daysFromToday(7),
    status: 'active',
    notes: 'Unsweetened',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Avocados',
    category: 'Fruits',
    quantity: 3,
    unit: 'Pieces',
    entryDate: daysFromToday(-1),
    expiryDate: daysFromToday(5),
    status: 'active',
    notes: 'Hass variety, ripe',
    imageUrl: '',
  },
  {
    id: uuidv4(),
    name: 'Pasta',
    category: 'Grains',
    quantity: 500,
    unit: 'Grams',
    entryDate: daysFromToday(-20),
    expiryDate: daysFromToday(365),
    status: 'active',
    notes: 'Penne rigate',
    imageUrl: '',
  },
];

export const mockUser = {
  name: 'Alex Johnson',
  email: 'admin@pantrypal.com',
  avatar: '',
};

export const mockSettings = {
  alertDays: 3,
  showExpiredInDashboard: true,
  defaultUnit: 'Pieces',
  defaultCategory: 'Other',
  itemsPerPage: 10,
  browserNotifications: false,
  alertSound: false,
  theme: 'light',
};

export const categoryOptions = [
  { value: 'Dairy',      label: 'Dairy',      icon: '🥛', color: 'cat-dairy' },
  { value: 'Vegetables', label: 'Vegetables', icon: '🥦', color: 'cat-vegetables' },
  { value: 'Fruits',     label: 'Fruits',     icon: '🍎', color: 'cat-fruits' },
  { value: 'Grains',     label: 'Grains',     icon: '🌾', color: 'cat-grains' },
  { value: 'Beverages',  label: 'Beverages',  icon: '🧃', color: 'cat-beverages' },
  { value: 'Meat',       label: 'Meat',       icon: '🥩', color: 'cat-meat' },
  { value: 'Other',      label: 'Other',      icon: '📦', color: 'cat-other' },
];

export const unitOptions = ['Pieces', 'Kg', 'Grams', 'Liters', 'Packs', 'Bottles', 'Dozen'];
